package shared

import "encoding/json"

// Represents an API error
type ProblemDetails struct {
	// The human-readable explanation specific to this occurrence of the error.
	Detail *string `json:"detail,omitempty" maxLength:"2000" minLength:"1"`
	// The URI reference that identifies the specific occurrence of the error.
	Instance *string `json:"instance,omitempty" maxLength:"2048" minLength:"1"`
	// The HTTP status code generated by the origin server for this occurrence of the error.
	Status *int64 `json:"status,omitempty" min:"100" max:"599"`
	// The short, human-readable summary of the error type.
	Title *string `json:"title,omitempty" maxLength:"2000" minLength:"1"`
	// The URI reference that identifies the error type.
	Type_ *string `json:"type,omitempty" maxLength:"2048" minLength:"1"`
}

func (p *ProblemDetails) GetDetail() *string {
	if p == nil {
		return nil
	}
	return p.Detail
}

func (p *ProblemDetails) SetDetail(detail string) {
	p.Detail = &detail
}

func (p *ProblemDetails) GetInstance() *string {
	if p == nil {
		return nil
	}
	return p.Instance
}

func (p *ProblemDetails) SetInstance(instance string) {
	p.Instance = &instance
}

func (p *ProblemDetails) GetStatus() *int64 {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *ProblemDetails) SetStatus(status int64) {
	p.Status = &status
}

func (p *ProblemDetails) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

func (p *ProblemDetails) SetTitle(title string) {
	p.Title = &title
}

func (p *ProblemDetails) GetType_() *string {
	if p == nil {
		return nil
	}
	return p.Type_
}

func (p *ProblemDetails) SetType_(type_ string) {
	p.Type_ = &type_
}

func (p ProblemDetails) String() string {
	jsonData, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return "error converting struct: ProblemDetails to string"
	}
	return string(jsonData)
}
