name: Publish Go Package

on:
  release:
    types:
      - published

env:
  MANIFEST_PATH: .manifest.json

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read module name
        id: read_module_name
        run: echo "module_name=$(jq -r '.config.languageOptions.go.goModuleName' $MANIFEST_PATH)" >> "$GITHUB_OUTPUT"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Install Dependencies
        run: go mod download
      - name: List Package to Request Indexing
        run: GOPROXY=proxy.golang.org go list -m ${{ steps.read_module_name.outputs.module_name }}
